module.exports = {
  ADMIN_SECRET: process.env.ADMIN_SECRET,
  HGE_ENDPOINT: process.env.HGE_ENDPOINT,
  SLACK_SIGNING_SECRET: process.env.SLACK_SIGNING_SECRET,
  SLACK_ACCESS_TOKEN: process.env.SLACK_ACCESS_TOKEN,
  SLACK_CLIENT_ID: process.env.SLACK_CLIENT_ID,
  SLACK_CLIENT_SECRET: process.env.SLACK_CLIENT_SECRET
};
